### ISSUE TITLE
new feature requests

### ISSUE THREAD

**Issue by mzelecom** [tallesl/net-Socket#1]
Hi
your library is very good for me.
i used it for multiclient server.
but i need to get my client ip (RemoteEndPoint) and your library doesn't have any method to get client ip.
and another feature that i need is knowing about client disconnected.
please add thesis feature to library.
thank you.

**Comment by tallesl** [comment]
Hi,

I'm surprised to see someone using the library!

There's a `UnderlyingSocket` property on the version [2.1.0](https://github.com/tallesl/net-Socket/releases/tag/2.1.0) (released just now) exposing the [System.Net.Sockets.Socket](https://msdn.microsoft.com/library/System.Net.Sockets.Socket) of the wrapper (which has the `RemoteEndPoint` that you need).

As for knowing about the client disconnect, well, there's several ways to tackle the problem. I'm afraid that it'll be on your shoulders. If you need any guidance, [this article](http://blog.stephencleary.com/2009/05/detection-of-half-open-dropped.html) is a great start.

P.S.: I've used this library only on prototypes and small use cases, it never reached production. Even though the code is fairly small, consider that while using it.
