### ISSUE TITLE
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by gardavis** [tallesl/net-Socket#2]
I am using this package to talk to my Tivo from Windows 10. It works for a while and then starts getting this error. Once it starts all requests fail like this.

```
Unhandled Exception: System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at SocketLibrary.ConnectedSocket.Receive(Int32 bufferSize) in a:\GitHub\net-Socket\Library\ConnectedSocket.cs:line 101
```

This is called by an Amazon Echo calling a web API running on my local web server via IIS. One command like to pause the Tivo will open the connection, send the pause command, read the response (ignored) and return from the API.

Thanks
Gary

**Comment by tallesl** [comment]
I'm so sorry to let you hang here (2016), but the fact is that I'm not using the library anymore (and never came to use it in production).

Anyway, why do you think there's an issue here? Maybe the error message is saying exactly what's happening ("An existing connection was forcibly closed by the remote host"), in other words, are you sure that the other side of the communication didn't just decide to close its end?
