### ISSUE TITLE
Start listening

### ISSUE THREAD

**Issue by GodStar88** [tallesl/net-Socket#3]
Hello, I am a C# developer.
            using (var listener = new SocketListener(1337)) // Start listening
            {
                for (; ; )
                {
                    using (var remote = listener.Accept()) // Accepts a connection (blocks execution)
                    {
                        var data = remote.Receive(); // Receives data (blocks execution)
                        remote.Send(data); // Sends the received data back
                    }
                }
            }
I used this code, when the run the code, I got UEE.
only one usage of each socket address (protocol/network, address/port) is normally permiitted

**Comment by tallesl** [comment]
Are you sure you weren't mistakenly running the example twice? (You can't have two applications listening for the same port).

Can you reproduce it again?
